// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/decks/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/decks/[id].get').default>>>>
    }
    '/api/decks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/decks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/decks/index.post').default>>>>
    }
    '/api/kanji/compounds': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kanji/compounds.get').default>>>>
    }
    '/api/kanji/details': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kanji/details.get').default>>>>
    }
    '/api/kanji/examples': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kanji/examples.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kanji/examples.post').default>>>>
    }
    '/api/ping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ping.get').default>>>>
    }
    '/api/word/details': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/word/details.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}